//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCatedraMDB.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriaPrecioProductos
    {
        public int IdAuditoria { get; set; }
        public int IdProducto { get; set; }
        public string NombreProducto { get; set; }
        public decimal PrecioAnterior { get; set; }
        public decimal PrecioNuevo { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public string UsuarioCambio { get; set; }
    }
}
