//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCatedraMDB.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoProductos
    {
        public int IdIngreso { get; set; }
        public int IdProducto { get; set; }
        public int IdProveedor { get; set; }
        public int CantidadIngreso { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaIngreso { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
